name: Build and Deploy Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze-code:
    name: Analyze Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run static code analysis
        run: mvn checkstyle:check

  build:
    name: Build JAR
    runs-on: ubuntu-latest
    needs: analyze-code

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar

  save-artifact:
    name: Save JAR to Repository
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: ./downloaded-artifact

      - name: List files in downloaded-artifact directory
        run: ls -al downloaded-artifact

      - name: Move JAR to artifacts directory
        run: |
          mkdir -p artifacts
          cp downloaded-artifact/*.jar artifacts/

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and push JAR
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git add artifacts/*.jar
          git commit -m "Add built JAR to repository"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin main
